src/lib/datastructures/test/bin/ola_f32_test : src/lib/datastructures/test/ola_f32_test.c \
                                               src/lib/datastructures/ola_f32.c
	$(CC) -g -Isrc/lib/datastructures -Isrc/test $^ -o $@
